development:
  adapter: postgresql
  encoding: unicode
  database: storyboard_development
  pool: 5
  username: cbastable
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: storyboard_test
  pool: 5
  username: cbastable
  password: